// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Otobur.Data;

#nullable disable

namespace Otobur.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250621182539_AksesyonDummy")]
    partial class AksesyonDummy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AksesyonDefteri", b =>
                {
                    b.Property<string>("AksesyonNumarasi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BitkininAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Koken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Koordinat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokasyon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MateryalCesidi")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToplanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToplayiciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplayiciKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToplayiciNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AksesyonNumarasi");

                    b.ToTable("AksesyonNumarasi");

                    b.HasData(
                        new
                        {
                            AksesyonNumarasi = "2023-00345",
                            BitkininAdi = "Pinus pinea",
                            Koken = "Kültür; Köken bilinmiyor",
                            Koordinat = "-",
                            Lokasyon = "-",
                            MateryalCesidi = 0,
                            ToplanmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToplayiciAdi = "-",
                            ToplayiciKodu = "-",
                            ToplayiciNumarasi = "-"
                        },
                        new
                        {
                            AksesyonNumarasi = "2023-00346",
                            BitkininAdi = "Cedrus libani",
                            Koken = "Köken bilgisi yok",
                            Koordinat = "-",
                            Lokasyon = "-",
                            MateryalCesidi = 0,
                            ToplanmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToplayiciAdi = "-",
                            ToplayiciKodu = "-",
                            ToplayiciNumarasi = "-"
                        },
                        new
                        {
                            AksesyonNumarasi = "2023-00347",
                            BitkininAdi = "Aethionema turcica",
                            Koken = "Doğal",
                            Koordinat = "39°52'45.34'' K - 32°15'43.45'' D",
                            Lokasyon = "Ankara; Beypazarı, Çakal gölü, 1750 m",
                            MateryalCesidi = 1,
                            ToplanmaTarihi = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToplayiciAdi = "Asil Güner",
                            ToplayiciKodu = "AG",
                            ToplayiciNumarasi = "12321"
                        },
                        new
                        {
                            AksesyonNumarasi = "2023-00348",
                            BitkininAdi = "Cota tinctoria",
                            Koken = "Kültür; Köken Biliniyor",
                            Koordinat = "-",
                            Lokasyon = "-",
                            MateryalCesidi = 1,
                            ToplanmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToplayiciAdi = "-",
                            ToplayiciKodu = "-",
                            ToplayiciNumarasi = "-"
                        },
                        new
                        {
                            AksesyonNumarasi = "2023-00349",
                            BitkininAdi = "Mespilus germanica",
                            Koken = "Kültür; Köken Biliniyor",
                            Koordinat = "-",
                            Lokasyon = "-",
                            MateryalCesidi = 2,
                            ToplanmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToplayiciAdi = "-",
                            ToplayiciKodu = "-",
                            ToplayiciNumarasi = "-"
                        },
                        new
                        {
                            AksesyonNumarasi = "2023-00350",
                            BitkininAdi = "Malus sylvestris",
                            Koken = "Kültür; Köken Biliniyor",
                            Koordinat = "-",
                            Lokasyon = "-",
                            MateryalCesidi = 0,
                            ToplanmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToplayiciAdi = "-",
                            ToplayiciKodu = "-",
                            ToplayiciNumarasi = "-"
                        },
                        new
                        {
                            AksesyonNumarasi = "2023-00351",
                            BitkininAdi = "Aucuba japonica",
                            Koken = "Kültür; Köken Biliniyor",
                            Koordinat = "-",
                            Lokasyon = "-",
                            MateryalCesidi = 2,
                            ToplanmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToplayiciAdi = "-",
                            ToplayiciKodu = "-",
                            ToplayiciNumarasi = "-"
                        },
                        new
                        {
                            AksesyonNumarasi = "2023-00352",
                            BitkininAdi = "Pelargonium quercetorum",
                            Koken = "Doğal",
                            Koordinat = "41°12'32.12'' K - 38°34'26.87'' D",
                            Lokasyon = "Bitlis; Tatvan, Demir Dağı, 1350 m",
                            MateryalCesidi = 1,
                            ToplanmaTarihi = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToplayiciAdi = "Salih Sercan Kanoğlu",
                            ToplayiciKodu = "SKNG",
                            ToplayiciNumarasi = "4532"
                        },
                        new
                        {
                            AksesyonNumarasi = "2023-00353",
                            BitkininAdi = "Flueggea anatolica",
                            Koken = "Doğal",
                            Koordinat = "37°24'33.01'' K - 34°23'24.53'' D",
                            Lokasyon = "Mersin; Kadıncık Vadisi, 455 m",
                            MateryalCesidi = 1,
                            ToplanmaTarihi = new DateTime(2023, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToplayiciAdi = "Mahmut Can",
                            ToplayiciKodu = "MCAN",
                            ToplayiciNumarasi = "2345"
                        },
                        new
                        {
                            AksesyonNumarasi = "2023-00354",
                            BitkininAdi = "Thermopsis turcica",
                            Koken = "Doğal",
                            Koordinat = "39°23'13.45'' K - 31°23'15.42'' D",
                            Lokasyon = "Konya; Eber Gölü çevresi, 876 m",
                            MateryalCesidi = 1,
                            ToplanmaTarihi = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToplayiciAdi = "Birol Sever",
                            ToplayiciKodu = "BRLS",
                            ToplayiciNumarasi = "6754"
                        },
                        new
                        {
                            AksesyonNumarasi = "2023-00355",
                            BitkininAdi = "Crocus biflorus",
                            Koken = "Doğal",
                            Koordinat = "39°12'23.44'' K - 39°34'32.44'' D",
                            Lokasyon = "Erzincan; Keşiş Dağı, 1786 m",
                            MateryalCesidi = 3,
                            ToplanmaTarihi = new DateTime(2022, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToplayiciAdi = "Emrah Çelik",
                            ToplayiciKodu = "ECLK",
                            ToplayiciNumarasi = "1201"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
